# more on the YAML format: <http://en.wikipedia.org/wiki/YAML>
application: blog-app
version: 1
runtime: python
api_version: 1


handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.py
